quotes = [
	"America: The only country that matters. If you want to experience other 'cultures,' use an atlas or a ham radio.",
	"An ideal night out, to me, is stepping onto my porch area and grilling up a thick slab of something's flesh and then popping in a highlight reel from the WNBA.",
	"And I'll have the number eight.",
	"Another word for 'jokes' is 'lies'. I do not lie. Therefore, I do not joke.",
	"Any dog under fifty pounds is a cat and cats are useless.",
	"Are you going to tell a man that he can't fart in his own car?",
	"Barbecues should be about one thing: good shared meat.",
	"Birthdays were invented by Hallmark to sell cards.",
	"Breakfast food can serve many purposes.",
	"Busy? Impossible. I work for the government.",
	"Capitalism is the only way , It makes America great, England OK and France terrible.",
	"Capitalism: God's way of determining who is smart and who is poor.",
	"Child labor laws are ruining this country.",
	"Clear alcohols are for rich women on diets.",
	"Cowardice and weak-willed men, and hazelnuts.",
	"Creativity is for people with glasses who like to lie.",
	"Crying: Acceptable at funerals and the Grand Canyon.",
	"Dear frozen yogurt, you are the celery of desserts. Be ice cream or be nothing. Zero stars.",
	"I have an uncle who does yoga.",
	"Don't start chasing applause and acclaim. That way lies madness.",
	"Encapsulate the spirit of melancholy. Easy. Boom, a sad desk. Boom, sad wall. It's art. Anything is anything.",
	"Epic. and Private.",
	"Every two weeks I need to sand down my toe nails. They're too strong for clippers.",
	"Fishing is for sport only. Fish meat is practically a vegetable.",
	"Fishing relaxes me. It's like yoga, except I still get to kill something.",
	"Friends: one to three is sufficient.",
	"Gentlemen, wilderness weekend is upon us. There will be no video games, there will be no internet pads. This weekend you have two parents, me and mother nature.",
	"Give 100%. 110% is impossible. Only idiots recommend that. Only idiots recommend that.",
	"Give a man a fish and feed him for a day. Don't teach a man to fish, and feed yourself. He's a grown man. And fishing's not that hard.",
	"Great job, everyone. The reception will be held in each of our individual houses, alone.",
	"Haha, Euro-trash, I like that. That is indeed a garbage continent.",
	"Hey {}. This is Beth, my ex-wife Tammy's better looking sister.",
	"Hey, who wants to see me climb a tree?",
	"History began on July 4, 1776. Everything that happened before that was a mistake.",
	"I am submitting this menu from a Pawnee institution, J.J.'s Diner. Home of the world's best breakfast dish: The Four Horsemeals of the Eggporkalypse.",
	"I assumed this was obvious but in the future, I'd prefer not to be part of any conversation about which body oil is best.",
	"I call this turf 'n' turf. It's a 16-ounce T-bone and a 24-ounce porterhouse. Also, whiskey and a cigar. I am going to consume all of this at the same time because I am a free American.",
	"I can't think of anything more noble to go to war over, than bacon and eggs.",
	"",
	"I don't want to paint with a broad brush here, but every single contractor in the world is a miserable, incompetent thief.",
	"I have a hernia. I've had it for a while, and I've been ignoring it successfully. But uh, this morning, I made the mistake of sneezing. But as long as I sit still and don't move my head or torso, I'm good. I got this.",
	"I have accrued two hundred and twenty five personal days starting right now I'm using all of them. While I'm gone your in charge. Also, I keep a sizable supply of ground chuck in my desk. Remove it or it will begin to smell. Godspeed.",
	"I have an uncle who does yoga.",
	"I hope the rest of your day is cool beans.",
	"I know what I'm about son.",
	"I like saying 'No,' it lowers their enthusiasm.",
	"I like some changes. Like when I change a tree into a canoe, or a wife into an ex-wife.",
	"I like {}. He doesn't do a lot of work around here. He shows zero initiative. He's not a team player. He's never wanted to go that extra mile. {} is exactly what I'm looking for in a government employee.",
	"I love being a father but there are a few things I miss: Silence. The absence of noise. One single moment undisturbed by the sounds of a children's program called Doc McStuffins. There is no quiet anymore. There is only Doc McStuffins.",
	"I love Food and Stuff. It's where I buy all my food, and most of my stuff.",
	"I prefer quality over flash , that's why I refuse to write my signature in cursive.",
	"I regret nothing. The end.",
	"I think that all government is a waster of taxpayer money. My dream is to have the park system privatized and run entirely by for profit corporations, like Chuck E. Cheese. They have an impeccable business model.",
	"I was born ready. I'm Ron fucking Swanson.",
	"I work hard to make sure my department is as small and as ineffective as possible.",
	"I would rather bleed out than sit here and talk about my feelings for 10 minutes.",
	"I'd wish you the best of luck, but I believe luck is a concept created by the weak to explain their failures.",
	"I'll take that steak to go. Please and thank you.",
	"I'm a simple man. I like pretty, dark-haired women and breakfast food.",
	"I'm not interested in caring about people.",
	"I'm not interested in caring about people. I once worked with a guy for three years and never learned his name. Best friend I ever had. We still never talk sometimes.",
	"I've created this office as a symbol of how I feel about government. This sawed-off shotgun belonged to a local bootlegger. People who come in here to ask me for things have to stare right down the barrel, ",
	"I've cried twice in my life. Once when I was 7 and hit by a school bus. And then again when I heard that Li'l Sebastian had passed.",
	"I've said it before and I'll say it again, children are terrible artists. And artists are crooks.",
	"I'd Wish You The Best Of Luck, But I Believe Luck Is A Concept Created By The Weak To Explain Their Failures.",
	"If any of you need anything at all, too bad. Deal with your problems yourselves, like adults.",
	"If it doesn't have meat, it's a snack.",
	"If there were more food and fewer people, this would be a perfect party.",
	"In my opinion, not enough people have looked their dinner in the eyes and considered the circle of life.",
	"Is Star Wars the one with the wizard boy?",
	"It's always a good idea to demonstrate to your coworkers that you are capable of withstanding a tremendous amount of pain.",
	"It's pointless for a human to paint scenes of nature when they can go outside and stand in it.",
	"It's Always A Good Idea To Demonstrate To Your Coworkers That You Are Capable Of Withstanding A Tremendous Amount Of Pain.",
	"Just give me all the bacon and eggs you have. Wait , I worry what you heard was, 'Give me a lot of bacon and eggs.' What I said was, give me all the bacon and eggs you have. Do you understand?",
	"Keep your tears in your eyes, where they belong.",
	"{}, I got married twice, both times I was a lot older than those two, and both marriages ended in divorce and a burning effigy. Whose to say what works? You find somebody you like and you roll the dice. That's all anybody can do.",
	"Leslie, my first wife Tammy, tried throwing me a surprise birthday party. When I saw my friends hiding through the window, I drove to a gas station, called the cops, and told 'em people had broken into my home. I'm not big on surprises.",
	"Listen, I've eaten a commissary hamburger for lunch every day for twelve years. I just wanted to make sure this pointless health crusade won't affect the only part of my job that I like.",
	"Literally everything is a weapon, son. That folder, in my hands, is far deadlier than this bow of yours.",
	"Live your life how you want, but don't confuse drama with happiness.",
	"Metaphors? I hate metaphors. That's why my favorite book is Moby Dick. No frufu symbolism, just a good simple tale about a man who hates an animal.",
	"My first ex-wife's name is Tammy. My second ex-wife's name is Tammy. My Mom's name is Tamara, she goes by Tammy.",
	"My idea of a perfect government is one guy who sits in a small room at a desk, and the only thing he's allowed to decide is who to nuke. The man is chosen based on some kind of IQ test, and maybe also a physical tournament, like a decathlon. And women are brought to him, maybe, when he desires them.",
	"My name is Ron Swanson. I'm going to tell you everything you need to know about the miserable screwed up world of local government.",
	"My son is several weeks old. He is very familiar with the sound of power tools.",
	"Never half-ass two things. Whole-ass one thing.",
	"No home is complete without a proper toolbox. Here's April and Andy's: A hammer, a half-eaten pretzel, a baseball card, some cartridge that says Sonic and Hedgehog, a scissor half, a flashlight filled with jellybeans.",
	"Normally, if given the choice between doing something and nothing, I'd choose to do nothing. But I will do something if it helps someone else do nothing. I'd work all night if it meant nothing got done.",
	"OK, everyone: shut up! And look at me!",
	"On my deathbed, my final wish is to have my ex-wives rush to my side so I can use my dying breath to tell them both to go to hell one last time.",
	"On nights like this when the cold winds blow, the air is awash in the swirling eddies of our dream, come with me and find safe haven in a warm bathtub full of my jazz.",
	"One rage every three months is permitted. Try not to hurt anyone who doesn't deserve it.",
	"Passing the Buck. The last refuge of the cowardly and Blackhearted.",
	"People are idiots, {}.",
	"Put some alcohol in your mouth to block with words from coming out.",
	"Say what you want about organized religion, but those bastards knew how to construct an edifice.",
	"Since I am not a rabbit, no I do not.",
	"So you talked to Tammy? What's it like to stare into the eye of Satan's butthole?",
	"Sting like a bee, but do not float like a butterfly. That's ridiculous.",
	"Straight down the middle. No hook, no spin, no fuss. Anything more and this becomes figure skating.",
	"Strippers do nothing for me, but I will take a free breakfast buffet anytime, anyplace.",
	"Thank you friend, that really means a lot to me.",
	"That is a canvas sheet, the most versatile object known to man. It can be used to make tents, backpacks, shoes, stretchers, sails, tarpaulins, and I suppose, in the most dire of circumstances, it can be a surface on which to make art.",
	"That's a party platter, it serves twelve people.",
	"The crib I built, I'm giving to you and Ann. It's perfectly safe. I tested it by hitting it with my truck.",
	"The government is a greedy piglet that suckles on a taxpayer's teat until they have sore, chapped nipples.",
	"The key to burning an ex-wife effigy is to dip it in paraffin wax and then toss the flaming bottle of isopropyl alcohol from a safe distance. Do not stand too close when you light an ex-wife effigy.",
	"The less I know about other people's affairs, the happier I am. I'm not interested in caring about people. I once worked with a guy for three years and never learned his name. Best friend I ever had. We still never talk sometimes.",
	"The only reason anyone is going to this thing is because they're afraid of what Marlene will do to them if they don't. That women is tough. In 1994 I gave her a nickname, it's unrepeatable, but it stuck. It's my proudest accomplishment. It's the iron cock shredder of Pawnee.",
	"The only thing that's important at the end of the day is what's on your gravestone , your name.",
	"The whole point of this country is if you want to eat garbage, balloon up to 600 pounds and die of a heart attack at 43, you can! You are free to do so. To me, that's beautiful.",
	"There are only three ways to motivate people: money, fear, and hunger.",
	"There Are Only Three Ways To Motivate People: Money, Fear, And Hunger.",
	"There are three acceptable haircuts: high and tight, crew cut, buzz cut.",
	"There has never been a sadness that can't be cured by breakfast food.",
	"There is only one bad word: taxes.",
	"There will be no froof-y desserts. There will be no giant soap bubble guns. There will be no adult men in costumes. And most of all, there will be no f#^%ing vegetables.",
	"There's a new wind blowing in government, and I don't like it. All of a sudden there's all this federal money coming in, and Paul the City Manager is telling us to build parks. Start new community programs. It's horrifying.",
	"There's only one thing I hate more than lying: skim milk. Which is water that's lying about being milk.",
	"There's more than one crib tree in a forest. That's not a lesson, by the way, just a comment on lumber availability.",
	"There's Only One Thing I Hate More Than Lying: Skim Milk. Which Is Water That's Lying About Being Milk.",
	"This is a flying robot that I just shot out of the sky when it tried to deliver me a package.",
	"This is not government work, as such I treat it with care and attention.",
	"This one is not good reaching out for help when you need it is healthy What he said right here is not.",
	"TOM PUT ALL MY RECORDS INTO THIS RECTANGLE. THE SONGS JUST PLAY ONE AFTER THE OTHER. THIS IS AN EXCELLENT RECTANGLE.",
	"Turkey can never beat cow.",
	"Under my tutelage, you will grow from boys to men. From men into gladiators. And from gladiators into Swansons.",
	"Veganism is the sad result of a morally corrupt mind. Reconsider your life.",
	"Veganism is the sad result of a morally corrupt mind. Reconsider your life.",
	"We will get along just fine, though hopefully not too fine, because I am not looking for any new friends. End speech.",
	"Welcome to 'Visions of Nature.' This room has several paintings in it. Some are big, some are small. People did them and they're here now. I believe that after this is over, they'll be hung in government buildings. Why the government is involved in an art show is beyond me. I also think it's pointless for a human to paint scenes of nature when they could just go outside and stand in it. Anyway, please do not misinterpret the fact that I am talking right now as genuine interest in art and attempt to discuss it with me further. End of speech.",
	"Well I've never been one for meeting new people, or doing new things, or eating new types of food, or traveling outside of southern Indiana. I've had the same haircut since 1978 and I've driven the same car since 1991. I've used the same wooden comb for three decades. I have one bowl. I still get my milk delivered by horse.",
	"Well, I am not usually one for speeches. So, goodbye.",
	"What religion am I? Well I am practicing none of your damn business.",
	"When I eat, it is the food that is scared.",
	"When I walked in this morning and saw that the flag was half-mast, I thought 'All right, another bureaucrat ate it!",
	"When people get too chummy with me I like to call them by the wrong name to let them know I don't really care about them.",
	"When People Get Too Chummy With Me, I Like To Call Them By The Wrong Name To Let Them Know I Don't Really Care About Them.",
	"Why is everyone else so bad at eating?",
	"Why would anybody ever eat anything besides breakfast food?",
	"You had me at 'Meat Tornado.'",
	"You've accidentally given me the food that my food eats."
	]